// ======================================================================
// 이름 번역 매핑 (Fish + Bugs + Sea Creatures + Fossils)
// ======================================================================
/**
 * 영어 이름을 한국어 이름으로 변환하는 매핑 객체
 * 
 * 모여봐요 동물의 숲 게임의 아이템 원본 이름(영어)을 한국어 이름으로 변환합니다.
 * 물고기, 곤충, 해양생물, 화석의 모든 아이템 이름을 포함합니다.
 */
export const nameKoMap: Record<string, string> = {
  // 물고기
  "Anchovy": "멸치",
  "Angelfish": "천사어",
  "Arapaima": "피라루쿠",
  "Arowana": "아로와나",
  "Barred knifejaw": "돌돔",
  "Barreleye": "데메니기스",
  "Betta": "베타",
  "Black bass": "큰입배스",
  "Blowfish": "복어",
  "Blue marlin": "청새치",
  "Bluegill": "블루길",
  "Butterfly fish": "나비고기",
  "Carp": "잉어",
  "Catfish": "메기",
  "Char": "열목어",
  "Cherry salmon": "산천어",
  "Clown fish": "흰동가리",
  "Coelacanth": "실러캔스",
  "Crawfish": "가재",
  "Crucian carp": "붕어",
  "Dab": "가자미",
  "Dace": "황어",
  "Dorado": "도라도",
  "Football fish": "복어아목",
  "Freshwater goby": "동사리",
  "Frog": "개구리",
  "Gar": "가아",
  "Giant snakehead": "가물치",
  "Giant trevally": "무명갈전갱이",
  "Golden trout": "금송어",
  "Goldfish": "금붕어",
  "Great white shark": "상어",
  "Guppy": "구피",
  "Hammerhead shark": "귀상어",
  "Horse mackerel": "전갱이",
  "Killifish": "송사리",
  "King salmon": "왕연어",
  "Koi": "비단잉어",
  "Loach": "미꾸라지",
  "Mahi-mahi": "만새기",
  "Mitten crab": "참게",
  "Moray eel": "곰치",
  "Napoleonfish": "나폴레옹피시",
  "Neon tetra": "네온테트라",
  "Nibble fish": "닥터피시",
  "Oarfish": "산갈치",
  "Ocean sunfish": "개복치",
  "Olive flounder": "넙치",
  "Pale chub": "은어",
  "Pike": "강꼬치고기",
  "Piranha": "피라니아",
  "Pond smelt": "빙어",
  "Pop-eyed goldfish": "특눈 금붕어",
  "Puffer fish": "가시복",
  "Rainbowfish": "레인보우피시",
  "Ranchu goldfish": "난주",
  "Ray": "가오리",
  "Red snapper": "도미",
  "Ribbon eel": "리본장어",
  "Saddled bichir": "엔드리케리",
  "Salmon": "연어",
  "Saw shark": "톱상어",
  "Sea bass": "농어",
  "Sea butterfly": "클리오네",
  "Sea horse": "해마",
  "Snapping turtle": "늑대거북",
  "Soft-shelled turtle": "자라",
  "Squid": "오징어",
  "Stringfish": "일본연어",
  "Sturgeon": "철갑상어",
  "Suckerfish": "빨판상어",
  "Surgeonfish": "블루탱",
  "Sweetfish": "은어",
  "Tadpole": "올챙이",
  "Tilapia": "틸라피아",
  "Tuna": "다랑어",
  "Whale shark": "고래상어",
  "Yellow perch": "옐로우퍼치",
  "Zebra turkeyfish": "쏠배감팽",
  "Bitterling": "납줄개",

  // 곤충
  "agrias butterfly": "아그리아스나비",
  "ant": "개미",
  "Atlas moth": "아틀라스나방",
  "bagworm": "도롱이벌레",
  "banded dragonfly": "장수잠자리",
  "bell cricket": "방울벌레",
  "blue weevil beetle": "유포루스바구미",
  "brown cicada": "유지매미",
  "centipede": "지네",
  "cicada shell": "매미허물",
  "citrus long-horned beetle": "알락하늘소",
  "common bluebottle": "청띠제비나비",
  "common butterfly": "배추흰나비",
  "cricket": "귀뚜라미",
  "cyclommatus stag": "엘라푸스가위사슴벌레",
  "damselfly": "실잠자리",
  "darner dragonfly": "왕잠자리",
  "diving beetle": "물방개",
  "drone beetle": "풍이",
  "dung beetle": "쇠똥구리",
  "earth-boring dung beetle": "보라금풍뎅이",
  "emperor butterfly": "몰포나비",
  "evening cicada": "쓰르라미",
  "firefly": "반디",
  "flea": "벼룩",
  "fly": "파리",
  "giant cicada": "곰매미",
  "giant stag": "왕사슴벌레",
  "giant water bug": "물장군",
  "Giraffe Stag": "기라파톱사슴벌레",
  "Golden Stag": "황금사슴벌레",
  "Goliath Beetle": "골리앗왕꽃무지",
  "grasshopper": "여치",
  "great purple emperor": "왕오색나비",
  "hermit crab": "소라게",
  "honeybee": "꿀벌",
  "horned atlas": "코카서스장수풍뎅이",
  "horned dynastid": "장수풍뎅이",
  "horned elephant": "코끼리장수풍뎅이",
  "horned hercules": "헤라클레스풍뎅이",
  "Jewel Beetle": "비단벌레",
  "ladybug": "무당벌레",
  "long locust": "방아깨비",
  "Madagascan sunset moth": "마다가스카르비단제비나방",
  "man-faced stink bug": "인면노린재",
  "mantis": "사마귀",
  "migratory locust": "섬풀무치",
  "Miyama Stag": "사슴벌레",
  "mole cricket": "땅강아지",
  "monarch butterfly": "왕나비",
  "mosquito": "모기",
  "moth": "나방",
  "orchid mantis": "연꽃사마귀",
  "paper kite butterfly": "왕얼룩나비",
  "peacock butterfly": "제비나비",
  "Pill Bug": "공벌레",
  "pondskater": "소금쟁이",
  "Queen Alexandra's birdwing": "알렉산드라비단제비나비",
  "Rainbow Stag": "뮤엘러리사슴벌레",
  "Rajah Brooke's birdwing": "라자브룩왕관나비",
  "red dragonfly": "고추잠자리",
  "rice grasshopper": "메뚜기",
  "robust cicada": "참매미",
  "Rosalia Batesi Beetle": "루리하늘소",
  "Saw Stag": "톱사슴벌레",
  "Scarab Beetle": "보석풍뎅이",
  "scorpion": "전갈",
  "snail": "달팽이",
  "spider": "거미",
  "stinkbug": "노린재",
  "tarantula": "타란튤라",
  "tiger beetle": "길앞잡이",
  "tiger butterfly": "호랑나비",
  "Violin Beetle": "바이올린벌레",
  "Walker cicada": "애매미",
  "walking leaf": "잎사귀벌레",
  "walking stick": "긴수염대벌레",
  "wasp": "벌",
  "wharf roach": "갯강구",
  "Yellow butterfly": "노랑나비",

  // 🌊 해양생물
  "abalone": "전복",
  "acorn barnacle": "따개비",
  "chambered nautilus": "앵무조개",
  "Dungeness crab": "던지니스게",
  "firefly squid": "반딧불오징어",
  "flatworm": "납작벌레",
  "gazami crab": "꽃게",
  "giant isopod": "이소포드",
  "gigas giant clam": "거대대합",
  "horseshoe crab": "투구게",
  "lobster": "바닷가재",
  "mantis shrimp": "갯가재",
  "moon jellyfish": "보름달물해파리",
  "mussel": "지중해담치",
  "octopus": "문어",
  "oyster": "굴",
  "pearl oyster": "진주조개",
  "red king crab": "왕게",
  "scallop": "가리비",
  "sea anemone": "말미잘",
  "sea cucumber": "해삼",
  "sea grapes": "바다포도",
  "sea pig": "바다돼지",
  "sea pineapple": "멍게",
  "sea slug": "갯민숭달팽이",
  "sea star": "불가사리",
  "sea urchin": "성게",
  "seaweed": "미역",
  "slate pencil urchin": "연필성게",
  "snow crab": "대게",
  "spider crab": "키다리게",
  "spiny lobster": "닭새우",
  "spotted garden eel": "가든일",
  "sweet shrimp": "북쪽분홍새우",
  "tiger prawn": "보리새우",
  "turban shell": "소라",
  "umbrella octopus": "우무문어",
  "vampire squid": "흡혈오징어",
  "Venus flower basket": "해로동혈",
  "whelk": "수랑",

  // 화석
  "ankylo skull": "안킬로사우루스 두개골",
  "ankylo tail": "안킬로사우루스 꼬리",
  "ankylo torso": "안킬로사우루스 몸통",
  "archelon skull": "아르켈론 두개골",
  "archelon tail": "아르켈론 꼬리",
  "brachio chest": "브라키오 가슴",
  "brachio pelvis": "브라키오 골반",
  "brachio skull": "브라키오 두개골",
  "brachio tail": "브라키오 꼬리",
  "deinony tail": "데이노니쿠스 꼬리",
  "deinony torso": "데이노니쿠스 몸통",
  "dimetrodon skull": "디메트로돈 두개골",
  "dimetrodon torso": "디메트로돈 몸통",
  "diplo chest": "디플로도쿠스 가슴",
  "diplo neck": "디플로도쿠스 목",
  "diplo pelvis": "디플로도쿠스 골반",
  "diplo skull": "디플로도쿠스 두개골",
  "diplo tail": "디플로도쿠스 꼬리",
  "diplo tail tip": "디플로도쿠스 꼬리끝",
  "iguanodon skull": "이구아노돈 두개골",
  "iguanodon tail": "이구아노돈 꼬리",
  "iguanodon torso": "이구아노돈 몸통",
  "mammoth skull": "매머드 두개골",
  "mammoth torso": "매머드 몸통",
  "megacero skull": "메가케로스 두개골",
  "megacero tail": "메가케로스 꼬리",
  "megacero torso": "메가케로스 몸통",
  "left megalo side": "메갈로 왼쪽몸통",
  "right megalo side": "메갈로 오른쪽몸통",
  "ophthalmo skull": "옵탈모사우루스 두개골",
  "ophthalmo torso": "옵탈모사우루스 몸통",
  "pachy skull": "파키케팔로사우루스 두개골",
  "pachy tail": "파키케팔로사우루스 꼬리",
  "parasaur skull": "파라사우롤로푸스 두개골",
  "parasaur tail": "파라사우롤로푸스 꼬리",
  "parasaur torso": "파라사우롤로푸스 몸통",
  "left ptera wing": "익룡 왼쪽날개",
  "ptera body": "익룡 몸통",
  "right ptera wing": "익룡 오른쪽날개",
  "left quetzal wing": "퀘찰코아틀루스 왼쪽날개",
  "quetzal torso": "퀘찰코아틀루스 몸통",
  "right quetzal wing": "퀘찰코아틀루스 오른쪽날개",
  "sabertooth skull": "검치호 두개골",
  "sabertooth tail": "검치호 꼬리",
  "spino skull": "스피노사우루스 두개골",
  "spino tail": "스피노사우루스 꼬리",
  "spino torso": "스피노사우루스 몸통",
  "stego skull": "스테고사우루스 두개골",
  "stego tail": "스테고사우루스 꼬리",
  "stego torso": "스테고사우루스 몸통",
  "T. rex skull": "티라노사우루스 두개골",
  "T. rex tail": "티라노사우루스 꼬리",
  "T. rex torso": "티라노사우루스 몸통",
  "tricera skull": "트리케라톱스 두개골",
  "tricera tail": "트리케라톱스 꼬리",
  "tricera torso": "트리케라톱스 몸통",
}

// ======================================================================
// 일본어 이름 매핑
// ======================================================================
/**
 * 일본어 이름을 한국어 이름으로 변환하는 매핑 객체
 */
export const nameJaMap: Record<string, string> = {
  // 물고기
  "タナゴ": "납줄개",
  "オイカワ": "피라미",
  "フナ": "붕어",
  "ウグイ": "황어",
  "コイ": "잉어",
  "ニシキゴイ": "비단잉어",
  "キンギョ": "금붕어",
  "デメキン": "특눈 금붕어",
  "ランチュウ": "난주",
  "メダカ": "송사리",
  "ザリガニ": "가재",
  "スッポン": "자라",
  "カミツキガメ": "늑대거북",
  "オタマジャクシ": "올챙이",
  "カエル": "개구리",
  "ドンコ": "동사리",
  "ドジョウ": "미꾸라지",
  "ナマズ": "메기",
  "ライギョ": "가물치",
  "ブルーギル": "블루길",
  "イエローパーチ": "옐로우퍼치",
  "ブラックバス": "큰입배스",
  "ティラピア": "틸라피아",
  "パイク": "강꼬치고기",
  "ワカサギ": "빙어",
  "アユ": "은어",
  "ヤマメ": "산천어",
  "オオイワナ": "열목어",
  "ゴールデントラウト": "금송어",
  "イトウ": "일본연어",
  "サケ": "연어",
  "キングサーモン": "왕연어",
  "シャンハイガニ": "참게",
  "グッピー": "구피",
  "ドクターフィッシュ": "닥터피시",
  "エンゼルフィッシュ": "천사어",
  "ベタ": "베타",
  "ネオンテトラ": "네온테트라",
  "レインボーフィッシュ": "레인보우피시",
  "ピラニア": "피라니아",
  "アロワナ": "아로와나",
  "ドラド": "도라도",
  "ガー": "가아",
  "ピラルク": "피라루쿠",
  "エンドリケリー": "엔드리케리",
  "チョウザメ": "철갑상어",
  "クリオネ": "클리오네",
  "タツノオトシゴ": "해마",
  "クマノミ": "흰동가리",
  "ナンヨウハギ": "블루탱",
  "チョウチョウウオ": "나비고기",
  "ナポレオンフィッシュ": "나폴레옹피시",
  "ミノカサゴ": "쏠배감팽",
  "フグ": "복어",
  "ハリセンボン": "가시복",
  "アンチョビ": "멸치",
  "アジ": "전갱이",
  "イシダイ": "돌돔",
  "スズキ": "농어",
  "タイ": "도미",
  "カレイ": "가자미",
  "ヒラメ": "넙치",
  "イカ": "오징어",
  "ウツボ": "곰치",
  "ハナヒゲウツボ": "리본장어",
  "マグロ": "다랑어",
  "カジキ": "청새치",
  "ロウニンアジ": "무명갈전갱이",
  "シイラ": "만새기",
  "マンボウ": "개복치",
  "エイ": "가오리",
  "ノコギリザメ": "톱상어",
  "シュモクザメ": "귀상어",
  "サメ": "상어",
  "ジンベエザメ": "고래상어",
  "コバンザメ": "빨판상어",
  "チョウチンアンコウ": "초롱아귀",
  "リュウグウノツカイ": "산갈치",
  "デメニギス": "데메니기스",
  "シーラカンス": "실러캔스",
  // 해양생물
  "ワカメ": "미역",
  "ウミブドウ": "바다포도",
  "ナマコ": "해삼",
  "センジュナマコ": "바다돼지",
  "ヒトデ": "불가사리",
  "ウニ": "성게",
  "パイプウニ": "연필성게",
  "イソギンチャク": "말미잘",
  "ミズクラゲ": "보름달물해파리",
  "ウミウシ": "갯민숭달팽이",
  "アコヤガイ": "진주조개",
  "ムールガイ": "지중해담치",
  "オイスター": "굴",
  "ホタテ": "가리비",
  "バイガイ": "수랑",
  "サザエ": "소라",
  "アワビ": "전복",
  "オオシャコガイ": "대왕거거",
  "オウムガイ": "앵무조개",
  "タコ": "문어",
  "メンダコ": "우무문어",
  "コウモリダコ": "흡혈오징어",
  "ホタルイカ": "반딧불오징어",
  "ガザミ": "꽃게",
  "ダンジネスクラブ": "던지니스크랩",
  "ズワイガニ": "대게",
  "タラバガニ": "왕게",
  "フジツボ": "따개비",
  "タカアシガニ": "키다리게",
  "クルマエビ": "보리새우",
  "アマエビ": "북쪽분홍새우",
  "シャコ": "갯가재",
  "イセエビ": "닭새우",
  "ロブスター": "바닷가재",
  "ダイオウグソクムシ": "자이언트 이소포드",
  "カブトガニ": "투구게",
  "ホヤ": "멍게",
  "チンアナゴ": "가든일",
  "ヒラムシ": "납작벌레",
  "カイロウドウケツ": "해로동혈",
  // 곤충
  "モンシロチョウ": "배추흰나비",
  "モンキチョウ": "노랑나비",
  "アゲハチョウ": "호랑나비",
  "カラスアゲハ": "제비나비",
  "アオスジアゲハ": "청띠제비나비",
  "オオゴマダラ": "왕얼룩나비",
  "オオムラサキ": "왕오색나비",
  "オオカバマダラ": "왕나비",
  "モルフォチョウ": "몰포나비",
  "ミイロタテハ": "아그리아스나비",
  "アカエリトリバネアゲハ": "붉은목도리비단나비",
  "アレキサンドラトリバネアゲハ": "알렉산드라비단제비나비",
  "ガ": "나방",
  "ヨナグニサン": "아틀라스나방",
  "ニシキオオツバメガ": "마다가스카르비단제비나방",
  "ショウリョウバッタ": "방아깨비",
  "トノサマバッタ": "섬풀무치",
  "イナゴ": "메뚜기",
  "キリギリス": "여치",
  "コオロギ": "귀뚜라미",
  "スズムシ": "방울벌레",
  "カマキリ": "사마귀",
  "ハナカマキリ": "연꽃사마귀",
  "ミツバチ": "꿀벌",
  "ハチ": "벌",
  "アブラゼミ": "유지매미",
  "ミンミンゼミ": "참매미",
  "クマゼミ": "곰매미",
  "ツクツクホウシ": "애매미",
  "ヒグラシ": "쓰르라미",
  "セミのぬけがら": "매미허물",
  "アキアカネ": "고추잠자리",
  "ギンヤンマ": "왕잠자리",
  "オニヤンマ": "장수잠자리",
  "イトトンボ": "실잠자리",
  "ホタル": "반디",
  "オケラ": "땅강아지",
  "アメンボ": "소금쟁이",
  "ゲンゴロウ": "물방개",
  "タガメ": "물장군",
  "カメムシ": "노린재",
  "ジンメンカメムシ": "인면노린재",
  "てんとう虫": "무당벌레",
  "ハンミョウ": "길앞잡이",
  "タマムシ": "비단벌레",
  "バイオリンムシ": "바이올린벌레",
  "ゴマダラカミキリ": "알락하늘소",
  "ルリボシカミキリ": "루리하늘소",
  "ホウセキゾウムシ": "유포루스바구미",
  "フンコロガシ": "쇠똥구리",
  "オオセンチコガネ": "보라금풍뎅이",
  "プラチナコガネ": "보석풍뎅이",
  "カナブン": "풍이",
  "ゴライアスオオツノハナムグリ": "골리앗왕꽃무지",
  "ノコギリクワガタ": "톱사슴벌레",
  "ミヤマクワガタ": "사슴벌레",
  "オオクワガタ": "왕사슴벌레",
  "ニジイロクワガタ": "뮤엘러리사슴벌레",
  "ホソアカクワガタ": "엘라푸스가위사슴벌레",
  "オウゴンオニクワガタ": "황금사슴벌레",
  "ギラファノコギリクワガタ": "기라파톱사슴벌레",
  "カブトムシ": "장수풍뎅이",
  "コーカサスオオカブト": "코카서스장수풍뎅이",
  "ゾウカブト": "코끼리장수풍뎅이",
  "ヘラクレスオオカブト": "헤라클레스풍뎅이",
  "ナナフシ": "긴수염대벌레",
  "コノハムシ": "잎사귀벌레",
  "ミノムシ": "도롱이벌레",
  "アリ": "개미",
  "ヤドカリ": "소라게",
  "フナムシ": "갯강구",
  "ハエ": "파리",
  "カ": "모기",
  "ノミ": "벼룩",
  "カタツムリ": "달팽이",
  "ダンゴムシ": "공벌레",
  "ムカデ": "지네",
  "クモ": "거미",
  "タランチュラ": "타란튤라",
  "サソリ": "전갈",
}

/**
 * 일본어 이름을 영어 이름으로 변환하는 매핑 객체
 */
export const nameEnFromJaMap: Record<string, string> = {
  // 물고기
  "タナゴ": "Bitterling",
  "オイカワ": "Pale chub",
  "フナ": "Crucian carp",
  "ウグイ": "Dace",
  "コイ": "Carp",
  "ニシキゴイ": "Koi",
  "キンギョ": "Goldfish",
  "デメキン": "Pop-eyed goldfish",
  "ランチュウ": "Ranchu goldfish",
  "メダカ": "Killifish",
  "ザリガニ": "Crawfish",
  "スッポン": "Soft-shelled turtle",
  "カミツキガメ": "Snapping turtle",
  "オタマジャクシ": "Tadpole",
  "カエル": "Frog",
  "ドンコ": "Freshwater goby",
  "ドジョウ": "Loach",
  "ナマズ": "Catfish",
  "ライギョ": "Giant snakehead",
  "ブルーギル": "Bluegill",
  "イエローパーチ": "Yellow perch",
  "ブラックバス": "Black bass",
  "ティラピア": "Tilapia",
  "パイク": "Pike",
  "ワカサギ": "Pond smelt",
  "アユ": "Sweetfish",
  "ヤマメ": "Cherry salmon",
  "オオイワナ": "Char",
  "ゴールデントラウト": "Golden trout",
  "イトウ": "Stringfish",
  "サケ": "Salmon",
  "キングサーモン": "King salmon",
  "シャンハイガニ": "Mitten crab",
  "グッピー": "Guppy",
  "ドクターフィッシュ": "Nibble fish",
  "エンゼルフィッシュ": "Angelfish",
  "ベタ": "Betta",
  "ネオンテトラ": "Neon tetra",
  "レインボーフィッシュ": "Rainbowfish",
  "ピラニア": "Piranha",
  "アロワナ": "Arowana",
  "ドラド": "Dorado",
  "ガー": "Gar",
  "ピラルク": "Arapaima",
  "エンドリケリー": "Saddled bichir",
  "チョウザメ": "Sturgeon",
  "クリオネ": "Sea butterfly",
  "タツノオトシゴ": "Sea horse",
  "クマノミ": "Clown fish",
  "ナンヨウハギ": "Surgeonfish",
  "チョウチョウウオ": "Butterfly fish",
  "ナポレオンフィッシュ": "Napoleonfish",
  "ミノカサゴ": "Zebra turkeyfish",
  "フグ": "Blowfish",
  "ハリセンボン": "Puffer fish",
  "アンチョビ": "Anchovy",
  "アジ": "Horse mackerel",
  "イシダイ": "Barred knifejaw",
  "スズキ": "Sea bass",
  "タイ": "Red snapper",
  "カレイ": "Dab",
  "ヒラメ": "Olive flounder",
  "イカ": "Squid",
  "ウツボ": "Moray eel",
  "ハナヒゲウツボ": "Ribbon eel",
  "マグロ": "Tuna",
  "カジキ": "Blue marlin",
  "ロウニンアジ": "Giant trevally",
  "シイラ": "Mahi-mahi",
  "マンボウ": "Ocean sunfish",
  "エイ": "Ray",
  "ノコギリザメ": "Saw shark",
  "シュモクザメ": "Hammerhead shark",
  "サメ": "Great white shark",
  "ジンベエザメ": "Whale shark",
  "コバンザメ": "Suckerfish",
  "チョウチンアンコウ": "Football fish",
  "リュウグウノツカイ": "Oarfish",
  "デメニギス": "Barreleye",
  "シーラカンス": "Coelacanth",
  // 해양생물
  "ワカメ": "Seaweed",
  "ウミブドウ": "Sea grapes",
  "ナマコ": "Sea cucumber",
  "センジュナマコ": "Sea pig",
  "ヒトデ": "Sea star",
  "ウニ": "Sea urchin",
  "パイプウニ": "Slate pencil urchin",
  "イソギンチャク": "Sea anemone",
  "ミズクラゲ": "Moon jellyfish",
  "ウミウシ": "Sea slug",
  "アコヤガイ": "Pearl oyster",
  "ムールガイ": "Mussel",
  "オイスター": "Oyster",
  "ホタテ": "Scallop",
  "バイガイ": "Whelk",
  "サザエ": "Turban shell",
  "アワビ": "Abalone",
  "オオシャコガイ": "Gigas giant clam",
  "オウムガイ": "Chambered nautilus",
  "タコ": "Octopus",
  "メンダコ": "Umbrella octopus",
  "コウモリダコ": "Vampire squid",
  "ホタルイカ": "Firefly squid",
  "ガザミ": "Gazami crab",
  "ダンジネスクラブ": "Dungeness crab",
  "ズワイガニ": "Snow crab",
  "タラバガニ": "Red king crab",
  "フジツボ": "Acorn barnacle",
  "タカアシガニ": "Spider crab",
  "クルマエビ": "Tiger prawn",
  "アマエビ": "Sweet shrimp",
  "シャコ": "Mantis shrimp",
  "イセエビ": "Spiny lobster",
  "ロブスター": "Lobster",
  "ダイオウグソクムシ": "Giant isopod",
  "カブトガニ": "Horseshoe crab",
  "ホヤ": "Sea pineapple",
  "チンアナゴ": "Spotted garden eel",
  "ヒラムシ": "Flatworm",
  "カイロウドウケツ": "Venus flower basket",
  // 곤충
  "モンシロチョウ": "Common Butterfly",
  "モンキチョウ": "Yellow Butterfly",
  "アゲハチョウ": "Tiger Butterfly",
  "カラスアゲハ": "Peacock Butterfly",
  "アオスジアゲハ": "Common Bluebottle",
  "オオゴマダラ": "Paper Kite Butterfly",
  "オオムラサキ": "Great Purple Emperor",
  "オオカバマダラ": "Monarch Butterfly",
  "モルフォチョウ": "Emperor Butterfly",
  "ミイロタテハ": "Agrias Butterfly",
  "アカエリトリバネアゲハ": "Rajah Brooke's birdwing",
  "アレキサンドラトリバネアゲハ": "Queen Alexandra's birdwing",
  "ガ": "Moth",
  "ヨナグニサン": "Atlas Moth",
  "ニシキオオツバメガ": "Madagascan sunset moth",
  "ショウリョウバッタ": "Long Locust",
  "トノサマバッタ": "Migratory Locust",
  "イナゴ": "Rice Grasshopper",
  "キリギリス": "Grasshopper",
  "コオロギ": "Cricket",
  "スズムシ": "Bell Cricket",
  "カマキリ": "Mantis",
  "ハナカマキリ": "Orchid Mantis",
  "ミツバチ": "Honeybee",
  "ハチ": "Wasp",
  "アブラゼミ": "Brown Cicada",
  "ミンミンゼミ": "Robust Cicada",
  "クマゼミ": "Giant Cicada",
  "ツクツクホウシ": "Walker Cicada",
  "ヒグラシ": "Evening Cicada",
  "セミのぬけがら": "Cicada Shell",
  "アキアカネ": "Red Dragonfly",
  "ギンヤンマ": "Darner Dragonfly",
  "オニヤンマ": "Banded Dragonfly",
  "イトトンボ": "Damselfly",
  "ホタル": "Firefly",
  "オケラ": "Mole Cricket",
  "アメンボ": "Pondskater",
  "ゲンゴロウ": "Diving Beetle",
  "タガメ": "Giant Water Bug",
  "カメムシ": "Stinkbug",
  "ジンメンカメムシ": "Man-faced Stink Bug",
  "てんとう虫": "Ladybug",
  "ハンミョウ": "Tiger Beetle",
  "タマムシ": "Jewel Beetle",
  "バイオリンムシ": "Violin Beetle",
  "ゴマダラカミキリ": "Citrus Long-horned Beetle",
  "ルリボシカミキリ": "Rosalia Batesi Beetle",
  "ホウセキゾウムシ": "Blue Weevil Beetle",
  "フンコロガシ": "Dung Beetle",
  "オオセンチコガネ": "Earth-boring Dung Beetle",
  "プラチナコガネ": "Scarab Beetle",
  "カナブン": "Drone Beetle",
  "ゴライアスオオツノハナムグリ": "Goliath Beetle",
  "ノコギリクワガタ": "Saw Stag",
  "ミヤマクワガタ": "Miyama Stag",
  "オオクワガタ": "Giant Stag",
  "ニジイロクワガタ": "Rainbow Stag",
  "ホソアカクワガタ": "Cyclommatus Stag",
  "オウゴンオニクワガタ": "Golden Stag",
  "ギラファノコギリクワガタ": "Giraffe Stag",
  "カブトムシ": "Horned Dynastid",
  "コーカサスオオカブト": "Horned Atlas",
  "ゾウカブト": "Horned Elephant",
  "ヘラクレスオオカブト": "Horned Herucles",
  "ナナフシ": "Walking Stick",
  "コノハムシ": "Walking Leaf",
  "ミノムシ": "Bagworm",
  "アリ": "Ant",
  "ヤドカリ": "Hermit Crab",
  "フナムシ": "Wharf Roach",
  "ハエ": "Fly",
  "カ": "Mosquito",
  "ノミ": "Flea",
  "カタツムリ": "Snail",
  "ダンゴムシ": "Pill Bug",
  "ムカデ": "Centipede",
  "クモ": "Spider",
  "タランチュラ": "Tarantula",
  "サソリ": "Scorpion",
}

// ======================================================================
// 위치 번역 매핑
// ======================================================================
/**
 * 영어 위치명을 한국어 위치명으로 변환하는 매핑 객체
 * 
 * 아이템이 잡히는 위치 정보를 한국어로 변환합니다.
 * 물고기, 곤충, 해양생물의 서식지 정보를 포함합니다.
 */
export const locationKoMap: Record<string, string> = {
  "Sea": "바다",
  "River": "강",
  "Pond": "연못",
  "Pier": "부두",
  "River (clifftop)": "절벽 위 강",
  "River (mouth)": "강 어귀",
  "Sea (raining)": "비 오는 바다",
  "Flying near flowers": "꽃 근처를 날아다님",
  "On/near spoiled turnips/candy/lollipops": "썩은무/사탕/롤리팝 근처",
  "On trees (any kind)": "모든 나무 위",
  "Shaking trees (hardwood and cedar)": "단단한 나무나 삼나무 흔들기",
  "Flying near water": "물 근처를 날아다님",
  "On the ground": "땅 위",
  "On palm trees": "야자수 위",
  "From hitting rocks": "바위를 두드리면 등장",
  "On tree stumps": "그루터기 위",
  "Flying": "공중에 떠 있음",
  "On rivers and ponds": "강과 연못 위",
  "Pushing snowballs": "눈덩이 굴리기",
  "On villagers": "주민에게 붙어 있음",
  "Flying near trash or rotten turnips": "쓰레기나 썩은무 근처를 날아다님",
  "Disguised on shoreline": "해변에서 위장 중",
  "On flowers": "꽃 위",
  "Underground": "지하",
  "Flying near light sources": "조명 근처를 날아다님",
  "On white flowers": "흰 꽃 위",
  "Flying near blue, purple, and black flowers": "파랑/보라/검정 꽃 근처를 날아다님",
  "Shaking trees": "나무를 흔들면 등장",
  "Disguised under trees": "나무 아래 위장 중",
  "Shaking non-fruit hardwood trees or cedar trees": "열매 없는 나무나 삼나무 흔들기",
  "On beach rocks": "해변 바위 위",
  "Museum": "박물관",
}

// ======================================================================
// 위치 번역 매핑 (영어 → 일본어)
// ======================================================================
export const locationJaMap: Record<string, string> = {
  "Sea": "海",
  "River": "川",
  "Pond": "池",
  "Pier": "桟橋",
  "River (clifftop)": "崖の上の川",
  "River (mouth)": "河口",
  "Sea (raining)": "海（雨の日）",
  "Flying near flowers": "花の近くを飛んでいる",
  "On/near spoiled turnips/candy/lollipops": "腐ったカブ/キャンディの近く",
  "On trees (any kind)": "木の上（種類問わず）",
  "Shaking trees (hardwood and cedar)": "広葉樹・針葉樹を揺する",
  "Flying near water": "水辺の近くを飛んでいる",
  "On the ground": "地面",
  "On palm trees": "ヤシの木の上",
  "From hitting rocks": "岩を叩くと出現",
  "On tree stumps": "切り株の上",
  "Flying": "空中",
  "On rivers and ponds": "川と池の上",
  "Pushing snowballs": "雪玉を転がす",
  "On villagers": "住民に付いている",
  "Flying near trash or rotten turnips": "ゴミや腐ったカブの近くを飛んでいる",
  "Disguised on shoreline": "海岸に擬態",
  "On flowers": "花の上",
  "Underground": "地中",
  "Flying near light sources": "光源の近くを飛んでいる",
  "On white flowers": "白い花の上",
  "Flying near blue, purple, and black flowers": "青/紫/黒の花の近くを飛んでいる",
  "Shaking trees": "木を揺すると出現",
  "Disguised under trees": "木の下に擬態",
  "Shaking non-fruit hardwood trees or cedar trees": "実のない広葉樹・針葉樹を揺する",
  "On beach rocks": "海辺の岩の上",
  "Museum": "博物館",
}

// ======================================================================
// 그림자 크기 번역 매핑 (3개국어)
// ======================================================================
const shadowSizeTriMap: Record<string, { ko: string; en: string; ja: string }> = {
  "특대(지느러미)": { ko: "특대(지느러미)", en: "Largest (Fin)", ja: "特大（ヒレ）" },
  "특대":           { ko: "특대",           en: "Largest",       ja: "特大" },
  "큼":             { ko: "큼",             en: "Large",         ja: "大" },
  "약간큼":         { ko: "약간큼",         en: "Medium-Large",  ja: "やや大" },
  "긴":             { ko: "긴",             en: "Narrow",        ja: "細長" },
  "중간":           { ko: "중간",           en: "Medium",        ja: "中" },
  "작음":           { ko: "작음",           en: "Small",         ja: "小" },
  "매우작음":       { ko: "매우작음",       en: "Smallest",      ja: "極小" },
  "Largest (Fin)":  { ko: "특대(지느러미)", en: "Largest (Fin)", ja: "特大（ヒレ）" },
  "Largest":        { ko: "특대",           en: "Largest",       ja: "特大" },
  "Large":          { ko: "큼",             en: "Large",         ja: "大" },
  "Medium-Large":   { ko: "약간큼",         en: "Medium-Large",  ja: "やや大" },
  "Narrow":         { ko: "긴",             en: "Narrow",        ja: "細長" },
  "Medium":         { ko: "중간",           en: "Medium",        ja: "中" },
  "Small":          { ko: "작음",           en: "Small",         ja: "小" },
  "Smallest":       { ko: "매우작음",       en: "Smallest",      ja: "極小" },
  "特大（ヒレ）":   { ko: "특대(지느러미)", en: "Largest (Fin)", ja: "特大（ヒレ）" },
  "特大":           { ko: "특대",           en: "Largest",       ja: "特大" },
  "大":             { ko: "큼",             en: "Large",         ja: "大" },
  "やや大":         { ko: "약간큼",         en: "Medium-Large",  ja: "やや大" },
  "細長":           { ko: "긴",             en: "Narrow",        ja: "細長" },
  "中":             { ko: "중간",           en: "Medium",        ja: "中" },
  "小":             { ko: "작음",           en: "Small",         ja: "小" },
  "極小":           { ko: "매우작음",       en: "Smallest",      ja: "極小" },
}

/**
 * 그림자 크기를 로케일에 맞게 변환
 * DB에 한국어/영어/일본어 어느 쪽이든 양방향 처리
 */
export function getLocalizedShadowSize(raw: string, locale: string): string {
  if (!raw) return ""
  const entry = shadowSizeTriMap[raw]
  if (!entry) return raw
  if (locale === "en") return entry.en
  if (locale === "ja") return entry.ja
  return entry.ko
}

// 한국어 → 영어 역매핑 (DB에 한국어가 저장된 경우 대비)
export const locationEnMap: Record<string, string> = Object.fromEntries(
  Object.entries(locationKoMap).map(([en, ko]) => [ko, en])
)

// 한국어 → 일본어 위치 역매핑
export const locationJaFromKoMap: Record<string, string> = Object.fromEntries(
  Object.entries(locationKoMap).map(([en, ko]) => [ko, locationJaMap[en] ?? en])
)

// 영어 → 한국어 이름 역매핑 (nameKoMap의 역매핑)
export const nameEnMap: Record<string, string> = Object.fromEntries(
  Object.entries(nameKoMap).map(([en, ko]) => [ko, en])
)

// 한국어 → 일본어 이름 역매핑
export const nameJaFromKoMap: Record<string, string> = Object.fromEntries(
  Object.entries(nameJaMap).map(([ja, ko]) => [ko, ja])
)

/**
 * 위치명을 로케일에 맞게 변환
 * @param rawLoc - DB에 저장된 위치명 (영어 또는 한국어)
 * @param locale - 'ko' | 'en' | 'ja'
 */
export function getLocalizedLocation(rawLoc: string, locale: string): string {
  if (!rawLoc) return locale === "en" ? "Unknown" : locale === "ja" ? "不明" : "알 수 없음"
  if (locale === "en") return locationEnMap[rawLoc] || rawLoc
  if (locale === "ja") return locationJaMap[rawLoc] || locationJaFromKoMap[rawLoc] || rawLoc
  return locationKoMap[rawLoc] || rawLoc
}

/**
 * 이름을 로케일에 맞게 변환
 * @param originalName - 영어 원본 이름
 * @param nameKo - 한국어 이름
 * @param locale - 'ko' | 'en' | 'ja'
 */
export function getLocalizedName(
  originalName: string,
  nameKo: string,
  locale: string
): string {
  if (locale === "en") return nameEnMap[nameKo] || originalName
  if (locale === "ja") return nameJaFromKoMap[nameKo] || originalName
  return nameKo || nameKoMap[originalName] || originalName
}
