// ======================================================================
// 🌏 이름 번역 매핑 (Fish + Bugs + Sea Creatures + Fossils)
// ======================================================================
/**
 * 영어 이름을 한국어 이름으로 변환하는 매핑 객체
 * 
 * 모여봐요 동물의 숲 게임의 아이템 원본 이름(영어)을 한국어 이름으로 변환합니다.
 * 물고기, 곤충, 해양생물, 화석의 모든 아이템 이름을 포함합니다.
 */
export const nameKoMap: Record<string, string> = {
  // 🐟 물고기
  "Anchovy": "멸치",
  "Angelfish": "천사어",
  "Arapaima": "피라루쿠",
  "Arowana": "아로와나",
  "Barred knifejaw": "돌돔",
  "Barreleye": "데메니기스",
  "Betta": "베타",
  "Black bass": "큰입배스",
  "Blowfish": "복어",
  "Blue marlin": "청새치",
  "Bluegill": "블루길",
  "Butterfly fish": "나비고기",
  "Carp": "잉어",
  "Catfish": "메기",
  "Char": "열목어",
  "Cherry salmon": "산천어",
  "Clown fish": "흰동가리",
  "Coelacanth": "실러캔스",
  "Crawfish": "가재",
  "Crucian carp": "붕어",
  "Dab": "가자미",
  "Dace": "황어",
  "Dorado": "도라도",
  "Football fish": "복어아목",
  "Freshwater goby": "동사리",
  "Frog": "개구리",
  "Gar": "가아",
  "Giant snakehead": "가물치",
  "Giant trevally": "무명갈전갱이",
  "Golden trout": "금송어",
  "Goldfish": "금붕어",
  "Great white shark": "상어",
  "Guppy": "구피",
  "Hammerhead shark": "귀상어",
  "Horse mackerel": "전갱이",
  "Killifish": "송사리",
  "King salmon": "왕연어",
  "Koi": "비단잉어",
  "Loach": "미꾸라지",
  "Mahi-mahi": "만새기",
  "Mitten crab": "참게",
  "Moray eel": "곰치",
  "Napoleonfish": "나폴레옹피시",
  "Neon tetra": "네온테트라",
  "Nibble fish": "닥터피시",
  "Oarfish": "산갈치",
  "Ocean sunfish": "개복치",
  "Olive flounder": "넙치",
  "Pale chub": "은어",
  "Pike": "강꼬치고기",
  "Piranha": "피라니아",
  "Pond smelt": "빙어",
  "Pop-eyed goldfish": "특눈 금붕어",
  "Puffer fish": "가시복",
  "Rainbowfish": "레인보우피시",
  "Ranchu goldfish": "난주",
  "Ray": "가오리",
  "Red snapper": "도미",
  "Ribbon eel": "리본장어",
  "Saddled bichir": "엔드리케리",
  "Salmon": "연어",
  "Saw shark": "톱상어",
  "Sea bass": "농어",
  "Sea butterfly": "클리오네",
  "Sea horse": "해마",
  "Snapping turtle": "늑대거북",
  "Soft-shelled turtle": "자라",
  "Squid": "오징어",
  "Stringfish": "일본연어",
  "Sturgeon": "철갑상어",
  "Suckerfish": "빨판상어",
  "Surgeonfish": "블루탱",
  "Sweetfish": "은어",
  "Tadpole": "올챙이",
  "Tilapia": "틸라피아",
  "Tuna": "다랑어",
  "Whale shark": "고래상어",
  "Yellow perch": "옐로우퍼치",
  "Zebra turkeyfish": "쏠배감팽",
  "Bitterling": "납줄개",

  // 🐛 곤충
  "agrias butterfly": "아그리아스나비",
  "ant": "개미",
  "Atlas moth": "아틀라스나방",
  "bagworm": "도롱이벌레",
  "banded dragonfly": "장수잠자리",
  "bell cricket": "방울벌레",
  "blue weevil beetle": "유포루스바구미",
  "brown cicada": "유지매미",
  "centipede": "지네",
  "cicada shell": "매미허물",
  "citrus long-horned beetle": "알락하늘소",
  "common bluebottle": "청띠제비나비",
  "common butterfly": "배추흰나비",
  "cricket": "귀뚜라미",
  "cyclommatus stag": "엘라푸스가위사슴벌레",
  "damselfly": "실잠자리",
  "darner dragonfly": "왕잠자리",
  "diving beetle": "물방개",
  "drone beetle": "풍이",
  "dung beetle": "쇠똥구리",
  "earth-boring dung beetle": "보라금풍뎅이",
  "emperor butterfly": "몰포나비",
  "evening cicada": "쓰르라미",
  "firefly": "반디",
  "flea": "벼룩",
  "fly": "파리",
  "giant cicada": "곰매미",
  "giant stag": "왕사슴벌레",
  "giant water bug": "물장군",
  "Giraffe Stag": "기라파톱사슴벌레",
  "Golden Stag": "황금사슴벌레",
  "Goliath Beetle": "골리앗왕꽃무지",
  "grasshopper": "여치",
  "great purple emperor": "왕오색나비",
  "hermit crab": "소라게",
  "honeybee": "꿀벌",
  "horned atlas": "코카서스장수풍뎅이",
  "horned dynastid": "장수풍뎅이",
  "horned elephant": "코끼리장수풍뎅이",
  "horned hercules": "헤라클레스풍뎅이",
  "Jewel Beetle": "비단벌레",
  "ladybug": "무당벌레",
  "long locust": "방아깨비",
  "Madagascan sunset moth": "마다가스카르비단제비나방",
  "man-faced stink bug": "인면노린재",
  "mantis": "사마귀",
  "migratory locust": "섬풀무치",
  "Miyama Stag": "사슴벌레",
  "mole cricket": "땅강아지",
  "monarch butterfly": "왕나비",
  "mosquito": "모기",
  "moth": "나방",
  "orchid mantis": "연꽃사마귀",
  "paper kite butterfly": "왕얼룩나비",
  "peacock butterfly": "제비나비",
  "Pill Bug": "공벌레",
  "pondskater": "소금쟁이",
  "Queen Alexandra's birdwing": "알렉산드라비단제비나비",
  "Rainbow Stag": "뮤엘러리사슴벌레",
  "Rajah Brooke's birdwing": "라자브룩왕관나비",
  "red dragonfly": "고추잠자리",
  "rice grasshopper": "메뚜기",
  "robust cicada": "참매미",
  "Rosalia Batesi Beetle": "루리하늘소",
  "Saw Stag": "톱사슴벌레",
  "Scarab Beetle": "보석풍뎅이",
  "scorpion": "전갈",
  "snail": "달팽이",
  "spider": "거미",
  "stinkbug": "노린재",
  "tarantula": "타란튤라",
  "tiger beetle": "길앞잡이",
  "tiger butterfly": "호랑나비",
  "Violin Beetle": "바이올린벌레",
  "Walker cicada": "애매미",
  "walking leaf": "잎사귀벌레",
  "walking stick": "긴수염대벌레",
  "wasp": "벌",
  "wharf roach": "갯강구",
  "Yellow butterfly": "노랑나비",

  // 🌊 해양생물
  "abalone": "전복",
  "acorn barnacle": "따개비",
  "chambered nautilus": "앵무조개",
  "Dungeness crab": "던지니스게",
  "firefly squid": "반딧불오징어",
  "flatworm": "납작벌레",
  "gazami crab": "꽃게",
  "giant isopod": "이소포드",
  "gigas giant clam": "거대대합",
  "horseshoe crab": "투구게",
  "lobster": "바닷가재",
  "mantis shrimp": "갯가재",
  "moon jellyfish": "보름달물해파리",
  "mussel": "지중해담치",
  "octopus": "문어",
  "oyster": "굴",
  "pearl oyster": "진주조개",
  "red king crab": "왕게",
  "scallop": "가리비",
  "sea anemone": "말미잘",
  "sea cucumber": "해삼",
  "sea grapes": "바다포도",
  "sea pig": "바다돼지",
  "sea pineapple": "멍게",
  "sea slug": "갯민숭달팽이",
  "sea star": "불가사리",
  "sea urchin": "성게",
  "seaweed": "미역",
  "slate pencil urchin": "연필성게",
  "snow crab": "대게",
  "spider crab": "키다리게",
  "spiny lobster": "닭새우",
  "spotted garden eel": "가든일",
  "sweet shrimp": "북쪽분홍새우",
  "tiger prawn": "보리새우",
  "turban shell": "소라",
  "umbrella octopus": "우무문어",
  "vampire squid": "흡혈오징어",
  "Venus flower basket": "해로동혈",
  "whelk": "수랑",

  // 🦴 화석
  "ankylo skull": "안킬로사우루스 두개골",
  "ankylo tail": "안킬로사우루스 꼬리",
  "ankylo torso": "안킬로사우루스 몸통",
  "archelon skull": "아르켈론 두개골",
  "archelon tail": "아르켈론 꼬리",
  "brachio chest": "브라키오 가슴",
  "brachio pelvis": "브라키오 골반",
  "brachio skull": "브라키오 두개골",
  "brachio tail": "브라키오 꼬리",
  "deinony tail": "데이노니쿠스 꼬리",
  "deinony torso": "데이노니쿠스 몸통",
  "dimetrodon skull": "디메트로돈 두개골",
  "dimetrodon torso": "디메트로돈 몸통",
  "diplo chest": "디플로도쿠스 가슴",
  "diplo neck": "디플로도쿠스 목",
  "diplo pelvis": "디플로도쿠스 골반",
  "diplo skull": "디플로도쿠스 두개골",
  "diplo tail": "디플로도쿠스 꼬리",
  "diplo tail tip": "디플로도쿠스 꼬리끝",
  "iguanodon skull": "이구아노돈 두개골",
  "iguanodon tail": "이구아노돈 꼬리",
  "iguanodon torso": "이구아노돈 몸통",
  "mammoth skull": "매머드 두개골",
  "mammoth torso": "매머드 몸통",
  "megacero skull": "메가케로스 두개골",
  "megacero tail": "메가케로스 꼬리",
  "megacero torso": "메가케로스 몸통",
  "left megalo side": "메갈로 왼쪽몸통",
  "right megalo side": "메갈로 오른쪽몸통",
  "ophthalmo skull": "옵탈모사우루스 두개골",
  "ophthalmo torso": "옵탈모사우루스 몸통",
  "pachy skull": "파키케팔로사우루스 두개골",
  "pachy tail": "파키케팔로사우루스 꼬리",
  "parasaur skull": "파라사우롤로푸스 두개골",
  "parasaur tail": "파라사우롤로푸스 꼬리",
  "parasaur torso": "파라사우롤로푸스 몸통",
  "left ptera wing": "익룡 왼쪽날개",
  "ptera body": "익룡 몸통",
  "right ptera wing": "익룡 오른쪽날개",
  "left quetzal wing": "퀘찰코아틀루스 왼쪽날개",
  "quetzal torso": "퀘찰코아틀루스 몸통",
  "right quetzal wing": "퀘찰코아틀루스 오른쪽날개",
  "sabertooth skull": "검치호 두개골",
  "sabertooth tail": "검치호 꼬리",
  "spino skull": "스피노사우루스 두개골",
  "spino tail": "스피노사우루스 꼬리",
  "spino torso": "스피노사우루스 몸통",
  "stego skull": "스테고사우루스 두개골",
  "stego tail": "스테고사우루스 꼬리",
  "stego torso": "스테고사우루스 몸통",
  "T. rex skull": "티라노사우루스 두개골",
  "T. rex tail": "티라노사우루스 꼬리",
  "T. rex torso": "티라노사우루스 몸통",
  "tricera skull": "트리케라톱스 두개골",
  "tricera tail": "트리케라톱스 꼬리",
  "tricera torso": "트리케라톱스 몸통",
};

// ======================================================================
// 📍 위치 번역 매핑
// ======================================================================
/**
 * 영어 위치명을 한국어 위치명으로 변환하는 매핑 객체
 * 
 * 아이템이 잡히는 위치 정보를 한국어로 변환합니다.
 * 물고기, 곤충, 해양생물의 서식지 정보를 포함합니다.
 */
export const locationKoMap: Record<string, string> = {
  "Sea": "바다",
  "River": "강",
  "Pond": "연못",
  "Pier": "부두",
  "River (clifftop)": "절벽 위 강",
  "River (mouth)": "강 어귀",
  "Sea (raining)": "비 오는 바다",
  "Flying near flowers": "꽃 근처를 날아다님",
  "On/near spoiled turnips/candy/lollipops": "썩은무/사탕/롤리팝 근처",
  "On trees (any kind)": "모든 나무 위",
  "Shaking trees (hardwood and cedar)": "단단한 나무나 삼나무 흔들기",
  "Flying near water": "물 근처를 날아다님",
  "On the ground": "땅 위",
  "On palm trees": "야자수 위",
  "From hitting rocks": "바위를 두드리면 등장",
  "On tree stumps": "그루터기 위",
  "Flying": "공중에 떠 있음",
  "On rivers and ponds": "강과 연못 위",
  "Pushing snowballs": "눈덩이 굴리기",
  "On villagers": "주민에게 붙어 있음",
  "Flying near trash or rotten turnips": "쓰레기나 썩은무 근처를 날아다님",
  "Disguised on shoreline": "해변에서 위장 중",
  "On flowers": "꽃 위",
  "Underground": "지하",
  "Flying near light sources": "조명 근처를 날아다님",
  "On white flowers": "흰 꽃 위",
  "Flying near blue, purple, and black flowers": "파랑/보라/검정 꽃 근처를 날아다님",
  "Shaking trees": "나무를 흔들면 등장",
  "Disguised under trees": "나무 아래 위장 중",
  "Shaking non-fruit hardwood trees or cedar trees": "열매 없는 나무나 삼나무 흔들기",
  "On beach rocks": "해변 바위 위",
  "Museum": "박물관",
};
